### ISSUE TITLE
ModelCreateMutation generates required fields for CharFields without null=True.

### ISSUE THREAD

**Issue by gghildyal** [0soft/graphene-django-plus#10]
Django discourages the use of null=True for CharFields (and other fields based on CharField, like URLField etc) - https://docs.djangoproject.com/en/3.0/ref/models/fields/#null.

But the mutation types generates required input parameters for such fields. It should look at the 'blank' property of the field for CharField and TextField to decide if it's required or not.

**Comment by gghildyal** [comment]
Although a pretty simple workaround is to define the required_fields meta option.

**Comment by bellini666** [comment]
Hi @gghildyal 

Hrm, I see what you mean. Yes, I agree with you. Most of the code is based on graphene's fields generation from django models and it mapps null to required (because most of the code is used for output).

Maybe we should force the required to consider blank? My only concern would be breaking the api too much =P. But maybe it is for the better!

**Comment by gghildyal** [comment]
Hi @bellini666 

You are right about the fact that its graphene's field generation that causes null fields to come up as required, so its an issue with this library per se. And given that theres is an easy workaround to it, I don't think it's a big issue.

**Comment by bellini666** [comment]
@gghildyal was thinking about this issue and I think it is correct to consider the `blank` for requireness. Am going to do a change about this today.
